# Generated by Django 4.2.26 on 2025-11-26 06:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_physical', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PublicationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('address', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('edition', models.CharField(blank=True, max_length=50)),
                ('isbn', models.CharField(blank=True, max_length=20, verbose_name='ISBN')),
                ('language', models.CharField(default='English', max_length=50)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('abstract', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('call_number', models.CharField(blank=True, max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('authors', models.ManyToManyField(related_name='publications', to='catalog.author')),
                ('publication_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='catalog.publicationtype')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='catalog.publisher')),
                ('subjects', models.ManyToManyField(blank=True, related_name='publications', to='catalog.subject')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('on_loan', 'On Loan'), ('in_transit', 'In Transit'), ('on_hold_shelf', 'On Hold Shelf'), ('processing', 'Processing'), ('missing', 'Missing'), ('damaged', 'Damaged'), ('withdrawn', 'Withdrawn')], default='available', max_length=20)),
                ('condition', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('acquisition_date', models.DateField(default=django.utils.timezone.now)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('times_borrowed', models.IntegerField(default=0)),
                ('last_borrowed_date', models.DateTimeField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='catalog.location')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.publication')),
            ],
            options={
                'ordering': ['barcode'],
            },
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['title'], name='catalog_pub_title_a285a2_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['call_number'], name='catalog_pub_call_nu_9faa0e_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['barcode'], name='catalog_ite_barcode_cd9cf9_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['status'], name='catalog_ite_status_e172ee_idx'),
        ),
    ]
