# Generated by Django 5.2.8 on 2025-11-29 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_backfill_normalized_isbn'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='publication',
            new_name='catalog_pub_normali_2bbeea_idx',
            old_name='catalog_publication_normisbn_idx',
        ),
    ]
