# Generated by Django 4.2.26 on 2025-11-26 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hold_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ready_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('ready', 'Ready for Pickup'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='waiting', max_length=20)),
                ('queue_position', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to=settings.AUTH_USER_MODEL)),
                ('pickup_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holds', to='catalog.location')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='catalog.publication')),
            ],
            options={
                'ordering': ['hold_date'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('renewal_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('returned', 'Returned'), ('overdue', 'Overdue'), ('overdue_returned', 'Overdue (Returned)'), ('lost', 'Lost')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to=settings.AUTH_USER_MODEL)),
                ('checkout_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkouts_processed', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='catalog.item')),
                ('return_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns_processed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-checkout_date'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('pre_due', 'Pre-Due Notice'), ('overdue', 'Overdue Notice'), ('hold_ready', 'Hold Ready'), ('hold_expiring', 'Hold Expiring')], max_length=20)),
                ('sent_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('email_subject', models.CharField(max_length=200)),
                ('email_body', models.TextField()),
                ('is_sent', models.BooleanField(default=False)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('hold', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='circulation.hold')),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='circulation.loan')),
            ],
            options={
                'ordering': ['-sent_date'],
            },
        ),
        migrations.CreateModel(
            name='InTransit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('receive_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_transit', 'In Transit'), ('received', 'Received')], default='in_transit', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transits_from', to='catalog.location')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transits', to='catalog.item')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transits_to', to='catalog.location')),
            ],
            options={
                'verbose_name_plural': 'Items in transit',
                'ordering': ['-send_date'],
            },
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['borrower', 'status'], name='circulation_borrowe_f2857a_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['due_date'], name='circulation_due_dat_cde580_idx'),
        ),
        migrations.AddIndex(
            model_name='hold',
            index=models.Index(fields=['borrower', 'status'], name='circulation_borrowe_eef59f_idx'),
        ),
        migrations.AddIndex(
            model_name='hold',
            index=models.Index(fields=['publication', 'status'], name='circulation_publica_53f7b2_idx'),
        ),
    ]
