# Generated by Django 5.2.8 on 2025-11-27 02:16

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_date']},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='email_body',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='email_subject',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_sent',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sent_date',
        ),
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='notification',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_sent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.TextField(default='You have a new notification.'),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='Notification', max_length=200),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('checkout', 'Item Checked Out'), ('checkin', 'Item Returned'), ('due_soon', 'Due Soon (3 days)'), ('overdue', 'Overdue Notice'), ('hold_ready', 'Hold Ready for Pickup'), ('hold_placed', 'Hold Placed Successfully'), ('hold_expiring', 'Hold Expiring Soon'), ('hold_cancelled', 'Hold Cancelled'), ('renewal', 'Item Renewed'), ('fine_added', 'Fine Added')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['borrower', 'is_read'], name='circulation_borrowe_9389e5_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_date'], name='circulation_created_2d7c4c_idx'),
        ),
    ]
