# Generated by Django 5.2.8 on 2025-11-27 02:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('circulation', '0002_alter_notification_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending Staff Approval'), ('approved', 'Approved - Ready for Pickup'), ('completed', 'Completed - Checked Out'), ('cancelled', 'Cancelled'), ('denied', 'Denied')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Optional notes from borrower')),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('staff_notes', models.TextField(blank=True, help_text='Staff notes/reason for denial')),
                ('pickup_by_date', models.DateTimeField(blank=True, help_text='Borrower must pick up by this date', null=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_requests', to=settings.AUTH_USER_MODEL)),
                ('loan', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_request', to='circulation.loan')),
                ('pickup_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkout_requests', to='catalog.location')),
                ('reserved_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_for_requests', to='catalog.item')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_requests', to='catalog.publication')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_checkout_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-request_date'],
                'indexes': [models.Index(fields=['borrower', 'status'], name='circulation_borrowe_98655a_idx'), models.Index(fields=['status', 'request_date'], name='circulation_status_a3e291_idx')],
            },
        ),
    ]
