# Generated by Django 5.2.8 on 2025-11-28 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0002_add_reserved_item'),
        ('circulation', '0004_add_reserved_item'),
    ]

    operations = [
    ]
