# Generated by Django 5.2.8 on 2025-12-12 00:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("circulation", "0005_merge_0002_add_reserved_item_0004_add_reserved_item"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checkout_notification", models.BooleanField(default=True)),
                ("checkin_notification", models.BooleanField(default=True)),
                ("due_soon_notification", models.BooleanField(default=True)),
                ("overdue_notification", models.BooleanField(default=True)),
                ("hold_ready_notification", models.BooleanField(default=True)),
                ("hold_placed_notification", models.BooleanField(default=False)),
                ("hold_expiring_notification", models.BooleanField(default=True)),
                ("renewal_notification", models.BooleanField(default=False)),
                ("fine_notification", models.BooleanField(default=True)),
                (
                    "default_channel",
                    models.CharField(
                        choices=[
                            ("in_app", "In-App Notification"),
                            ("email", "Email"),
                            ("both", "Both"),
                        ],
                        default="both",
                        max_length=10,
                    ),
                ),
                ("enable_sound_alerts", models.BooleanField(default=True)),
                (
                    "sound_volume",
                    models.IntegerField(
                        default=70,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("enable_email_digest", models.BooleanField(default=True)),
                (
                    "email_digest_frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("never", "Never"),
                        ],
                        default="weekly",
                        max_length=10,
                    ),
                ),
                ("last_digest_sent", models.DateTimeField(blank=True, null=True)),
                ("quiet_hours_enabled", models.BooleanField(default=False)),
                ("quiet_hours_start", models.TimeField(blank=True, null=True)),
                ("quiet_hours_end", models.TimeField(blank=True, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "borrower",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Notification Preferences",
            },
        ),
        migrations.CreateModel(
            name="SystemHealth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "database_size_mb",
                    models.FloatField(help_text="Database size in MB"),
                ),
                ("active_connections", models.IntegerField(default=0)),
                ("slow_queries", models.IntegerField(default=0)),
                (
                    "cpu_usage_percent",
                    models.FloatField(default=0, help_text="CPU usage percentage"),
                ),
                (
                    "memory_usage_percent",
                    models.FloatField(default=0, help_text="Memory usage percentage"),
                ),
                (
                    "disk_usage_percent",
                    models.FloatField(default=0, help_text="Disk usage percentage"),
                ),
                ("active_users", models.IntegerField(default=0)),
                ("total_requests", models.IntegerField(default=0)),
                ("failed_requests", models.IntegerField(default=0)),
                ("average_response_time_ms", models.FloatField(default=0)),
                ("cache_hits", models.IntegerField(default=0)),
                ("cache_misses", models.IntegerField(default=0)),
                ("error_count", models.IntegerField(default=0)),
                ("warning_count", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        default="healthy",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "System Health",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="circulation_timesta_ec4e3e_idx"
                    ),
                    models.Index(
                        fields=["status"], name="circulation_status_c3f62a_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "User Login"),
                            ("logout", "User Logout"),
                            ("checkout", "Item Checkout"),
                            ("checkin", "Item Check-in"),
                            ("renewal", "Item Renewal"),
                            ("hold_placed", "Hold Placed"),
                            ("hold_ready", "Hold Ready"),
                            ("publication_created", "Publication Created"),
                            ("publication_updated", "Publication Updated"),
                            ("publication_deleted", "Publication Deleted"),
                            ("user_created", "User Created"),
                            ("user_updated", "User Updated"),
                            ("user_deleted", "User Deleted"),
                            ("fine_added", "Fine Added"),
                            ("fine_waived", "Fine Waived"),
                            ("report_generated", "Report Generated"),
                            ("backup", "Backup Created"),
                            ("system_error", "System Error"),
                            ("permission_change", "Permission Changed"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "content_type",
                    models.CharField(
                        blank=True,
                        help_text="Model name (e.g., 'catalog.Publication')",
                        max_length=100,
                    ),
                ),
                ("object_id", models.IntegerField(blank=True, null=True)),
                ("object_repr", models.CharField(blank=True, max_length=200)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Activity Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="circulation_user_id_bcd5ed_idx",
                    ),
                    models.Index(
                        fields=["action", "timestamp"],
                        name="circulation_action_e62905_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="circulation_timesta_344c1b_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BackupLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "backup_type",
                    models.CharField(
                        choices=[
                            ("full", "Full Backup"),
                            ("incremental", "Incremental Backup"),
                            ("database", "Database Only"),
                            ("files", "Files Only"),
                        ],
                        default="full",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("backup_size_mb", models.FloatField(blank=True, null=True)),
                ("files_backed_up", models.IntegerField(default=0)),
                ("backup_path", models.CharField(blank=True, max_length=500)),
                (
                    "backup_location",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 'Local', 'Cloud', 'External Drive'",
                        max_length=100,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="backups_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-start_time"],
                "indexes": [
                    models.Index(
                        fields=["status", "start_time"],
                        name="circulation_status_c0f841_idx",
                    ),
                    models.Index(
                        fields=["start_time"], name="circulation_start_t_40c17d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationArchive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notification_type", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("created_date", models.DateTimeField()),
                ("archived_date", models.DateTimeField(auto_now_add=True)),
                (
                    "borrower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_archives",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-archived_date"],
                "indexes": [
                    models.Index(
                        fields=["borrower", "archived_date"],
                        name="circulation_borrowe_276d80_idx",
                    )
                ],
            },
        ),
    ]
